version: 2
models:
  - name: people
    # description: Join of product master data and P2S 
      
    columns:
      - name: product_active
        description: Is the product active?
        tests:
          - accepted_values:
              values: ['Y', 'N']

      - name: product_productId
        description: Id for the product 
        tests:
          - not_null